import {
  Brain,
  Shield,
  Users,
  Target,
  Scale,
  Network,
  ClipboardCheck,
  BarChart,
  Calendar,
  Video,
  Database,
  Zap,
  Lock,
  Mail,
  HardDrive,
  AlertTriangle,
  PieChart,
  Flame,
  TrendingUp,
  FileText,
  UserCheck,
  Eye,
  BookOpen,
  MessageCircle,
  Settings,
  Award,
  Send,
  Activity,
  HeartPulse,
  Globe,
  AlertCircle,
  Map,
  Cpu,
  Compass,
  GraduationCap,
  Code,
  Link,
  Handshake,
  DollarSign,
  UserPlus,
  CreditCard,
  ClipboardList,
  Search,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  brain: Brain,
  shield: Shield,
  users: Users,
  target: Target,
  scale: Scale,
  network: Network,
  clipboardCheck: ClipboardCheck,
  barChart: BarChart,
  calendar: Calendar,
  video: Video,
  database: Database,
  zap: Zap,
  lock: Lock,
  mail: Mail,
  hardDrive: HardDrive,
  alertTriangle: AlertTriangle,
  pieChart: PieChart,
  flame: Flame,
  trendingUp: TrendingUp,
  fileText: FileText,
  userCheck: UserCheck,
  eye: Eye,
  bookOpen: BookOpen,
  messageCircle: MessageCircle,
  settings: Settings,
  award: Award,
  send: Send,
  activity: Activity,
  heartPulse: HeartPulse,
  globe: Globe,
  alertCircle: AlertCircle,
  map: Map,
  cpu: Cpu,
  compass: Compass,
  graduationCap: GraduationCap,
  code: Code,
  link: Link,
  handshake: Handshake,
  dollarSign: DollarSign,
  userPlus: UserPlus,
  creditCard: CreditCard,
  clipboardList: ClipboardList,
  search: Search,
};
