import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import {
  Document, Packer, Paragraph, TextRun,
  HeadingLevel, AlignmentType, BorderStyle,
} from "docx";
import { assessmentDownloadSchema } from "@/lib/validation";

export async function POST(request: Request) {
  const session = await getServerSession(authOptions);
  if (!session?.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await request.json();
  const parsed = assessmentDownloadSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: "Invalid request" }, { status: 400 });
  }
  const { title, score, maxScore, percentage, recommendations } = parsed.data;
  const recs = (recommendations as string[]) || [];

  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({
          children: [new TextRun({ text: "KLO — KEITH L. ODOM", bold: true, size: 36, color: "2764FF" })],
        }),
        new Paragraph({
          children: [new TextRun({ text: "Strategic Technology Advisory", size: 18, color: "8B949E" })],
          spacing: { after: 200 },
        }),
        new Paragraph({
          children: [],
          border: { bottom: { color: "C8A84E", space: 1, style: BorderStyle.SINGLE, size: 6 } },
          spacing: { after: 400 },
        }),
        new Paragraph({
          text: title || "Assessment Report",
          heading: HeadingLevel.HEADING_1,
          spacing: { after: 300 },
        }),
        new Paragraph({
          children: [
            new TextRun({ text: "Score: ", bold: true, size: 24 }),
            new TextRun({ text: `${score} / ${maxScore} (${percentage}%)`, size: 24, color: "2764FF", bold: true }),
          ],
          spacing: { after: 400 },
        }),
        new Paragraph({
          text: "Recommendations",
          heading: HeadingLevel.HEADING_2,
          spacing: { after: 200 },
        }),
        ...recs.map((rec: string) =>
          new Paragraph({
            children: [new TextRun({ text: rec, size: 20, color: "8B949E" })],
            bullet: { level: 0 },
            spacing: { after: 100 },
          })
        ),
        new Paragraph({ children: [], spacing: { before: 600 } }),
        new Paragraph({
          children: [new TextRun({
            text: "Generated by klo-app.vercel.app — Book a consultation for personalized guidance",
            size: 16, color: "8B949E", italics: true,
          })],
          alignment: AlignmentType.CENTER,
        }),
      ],
    }],
  });

  const buffer = await Packer.toBuffer(doc);

  return new Response(new Uint8Array(buffer) as unknown as BodyInit, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "Content-Disposition": `attachment; filename="assessment-report.docx"`,
    },
  });
}
