import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { assessmentDownloadSchema } from "@/lib/validation";

export async function POST(request: Request) {
  const session = await getServerSession(authOptions);
  if (!session?.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await request.json();
  const parsed = assessmentDownloadSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: "Invalid request" }, { status: 400 });
  }
  const { title, score, maxScore, percentage, recommendations } = parsed.data;

  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]);
  const helvetica = await doc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const { height } = page.getSize();

  const blue = rgb(39 / 255, 100 / 255, 255 / 255);
  const gold = rgb(200 / 255, 168 / 255, 78 / 255);
  const darkGray = rgb(0.9, 0.93, 0.95);
  const gray = rgb(0.55, 0.58, 0.62);
  const bgColor = rgb(13 / 255, 17 / 255, 23 / 255);

  // Dark background
  page.drawRectangle({ x: 0, y: 0, width: 612, height: 792, color: bgColor });

  let y = height - 60;

  // Header
  page.drawText("KLO — KEITH L. ODOM", {
    x: 50, y, size: 22, font: helveticaBold, color: blue,
  });
  y -= 18;
  page.drawText("Strategic Technology Advisory", {
    x: 50, y, size: 10, font: helvetica, color: gray,
  });

  // Gold divider
  y -= 20;
  page.drawLine({ start: { x: 50, y }, end: { x: 562, y }, thickness: 2, color: gold });

  // Title
  y -= 40;
  page.drawText(title || "Assessment Report", {
    x: 50, y, size: 20, font: helveticaBold, color: darkGray,
  });

  // Score
  y -= 40;
  page.drawText("Score", { x: 50, y, size: 12, font: helveticaBold, color: darkGray });
  y -= 22;
  page.drawText(`${score} / ${maxScore} (${percentage}%)`, {
    x: 50, y, size: 18, font: helveticaBold, color: blue,
  });

  // Recommendations
  y -= 45;
  page.drawText("Recommendations", {
    x: 50, y, size: 14, font: helveticaBold, color: darkGray,
  });
  y -= 12;
  page.drawLine({ start: { x: 50, y }, end: { x: 562, y }, thickness: 0.5, color: rgb(0.3, 0.3, 0.35) });

  const recs = (recommendations as string[]) || [];
  for (const rec of recs) {
    y -= 25;
    if (y < 80) break;

    const maxWidth = 480;
    const words = rec.split(" ");
    let line = "";
    const lines: string[] = [];
    for (const word of words) {
      const testLine = line ? `${line} ${word}` : word;
      if (helvetica.widthOfTextAtSize(testLine, 10) > maxWidth && line) {
        lines.push(line);
        line = word;
      } else {
        line = testLine;
      }
    }
    if (line) lines.push(line);

    page.drawText("•", { x: 60, y, size: 10, font: helvetica, color: gold });
    for (let i = 0; i < lines.length; i++) {
      if (y - i * 14 < 60) break;
      page.drawText(lines[i], {
        x: 75, y: y - i * 14, size: 10, font: helvetica, color: gray,
      });
    }
    y -= (lines.length - 1) * 14;
  }

  // Footer
  page.drawText("Generated by klo-app.vercel.app — Book a consultation for personalized guidance", {
    x: 50, y: 30, size: 8, font: helvetica, color: gray,
  });

  const pdfBytes = await doc.save();

  return new Response(new Uint8Array(pdfBytes) as unknown as BodyInit, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="assessment-report.pdf"`,
    },
  });
}
